- name: Download stack
  get_url:
    url: "{{ stroom_url }}"
    dest: "./releases/"
    checksum: "sha256:{{ stroom_url }}.sha256"
  register: download_info

  # FIXME: I can't get this to work on macOS or Ubuntu. Ansible complains about /bin/tar not being able
  # to handle the archive. It untars manually without problems.
- name: Unpack Stroom's distribution tar
  unarchive:
    src: "{{playbook_dir}}/{{download_info.dest }}"
    dest: "./releases"
